name: CI

# Controls when the workflow will run
on:
  create:

  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      ReleaseType:
        description: 'Release or Debug'
        required: true
        default: 'Release'

jobs:
  Build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get Submodules
        run: git submodule update --init --recursive

      - name: Build ${{ github.event.inputs.ReleaseType || 'Release' }}
        run:  |
              if [ "$RUNNER_OS" == "Windows" ]; then
                ./ci-build.cmd ${{ github.event.inputs.ReleaseType || 'Release' }}
              else
                ./ci-build.sh ${{ github.event.inputs.ReleaseType || 'Release' }}
              fi
        shell: bash

      - name: Upload win-x64 ${{ github.event.inputs.ReleaseType || 'Release' }}
        uses: actions/upload-artifact@v3
        if: matrix.os == 'windows-latest'
        with:
          name: win-x64
          path: build\x64\${{ github.event.inputs.ReleaseType || 'Release' }}\*

      - name: Upload Linux ${{ github.event.inputs.ReleaseType || 'Release' }}
        uses: actions/upload-artifact@v3
        if: matrix.os == 'ubuntu-latest'
        with:
          name: linux-x64
          path: build/${{ github.event.inputs.ReleaseType || 'Release' }}/*

      - name: Upload MacOS ${{ github.event.inputs.ReleaseType || 'Release' }}
        uses: actions/upload-artifact@v3
        if: matrix.os == 'macos-latest'
        with:
          name: osx-x64
          path: build/${{ github.event.inputs.ReleaseType || 'Release' }}/*
